# ===================================================================
# 📡 Hostapd Configuration - WiFi Access Point
# ===================================================================

# ===================================================================
# Interface Settings
# ===================================================================

# WiFi interface
interface=wlxfc221c100d54

# Driver
driver=nl80211

# ===================================================================
# Network Settings
# ===================================================================

# Network name (SSID)
ssid=FreeWiFi

# Mode and channel
hw_mode=g
channel=6
wmm_enabled=1

# ===================================================================
# Security Settings
# ===================================================================

# Authentication
# 1 = WPA, 2 = WEP, 3 = both
#auth_algs=1        
# 2 WPA2 only or 0
wpa=0 
#wpa_passphrase=12345678
#wpa_key_mgmt=WPA-PSK
#wpa_pairwise=TKIP
rsn_pairwise=CCMP         

# ===================================================================
# Additional Settings
# ===================================================================

# Broadcast SSID
# 0 = broadcast, 1 = hidden
ignore_broadcast_ssid=0  

# MAC address control
# 0 = disabled, 1 = enabled
macaddr_acl=0    

# ===================================================================
# Logging
# ===================================================================

# Enable logging
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
